### ISSUE TITLE
Robot search function 

### ISSUE THREAD

**Issue by Krocko** [naofireblade/homebridge-neato#40]
Is it possible to add the search button to HomeKit?

**Comment by naofireblade** [comment]
Will be added soon in the next release.

**Comment by Krocko** [comment]
That is cool!

I tried the beta, but got an error.

```
[9/23/2019, 2:23:31 PM] Loaded config.json with 0 accessories and 1 platforms.
stdout
12:23:31
[9/23/2019, 2:23:31 PM] ---
stdout
12:23:31
[9/23/2019, 2:23:31 PM] Loaded plugin: homebridge-neato
stdout
12:23:31
[9/23/2019, 2:23:31 PM] Registering platform 'homebridge-neato.NeatoVacuumRobot'
stdout
12:23:31
[9/23/2019, 2:23:31 PM] ---
stdout
12:23:31
[9/23/2019, 2:23:31 PM] Loading 1 platforms...
stdout
12:23:31
[9/23/2019, 2:23:31 PM] [NeatoVacuumRobot] Initializing NeatoVacuumRobot platform...
stdout
12:23:31
[9/23/2019, 2:23:31 PM] [NeatoVacuumRobot] Refresh is set to: auto
stdout
12:23:31
[9/23/2019, 2:23:31 PM] Loading 0 accessories...
stdout
12:23:34
[9/23/2019, 2:23:34 PM] [NeatoVacuumRobot] Found robot #1 named "Elvis" with serial "xxxxxxxxxxxx"
stdout
12:23:34
[9/23/2019, 2:23:34 PM] [NeatoVacuumRobot] Adding zone cleaning for: Schlafzimmer
stdout
12:23:34
[9/23/2019, 2:23:34 PM] [NeatoVacuumRobot] Adding zone cleaning for: Esszimmer
stdout
12:23:34
[9/23/2019, 2:23:34 PM] [NeatoVacuumRobot] Adding zone cleaning for: Wohnzimmer
stdout
12:23:34
[9/23/2019, 2:23:34 PM] [NeatoVacuumRobot] Adding zone cleaning for: Flur
stdout
12:23:34
[9/23/2019, 2:23:34 PM] [NeatoVacuumRobot] Adding zone cleaning for: Kinderzimmer
stdout
12:23:34
[9/23/2019, 2:23:34 PM] [NeatoVacuumRobot] Adding zone cleaning for: Küche
stdout
12:23:34
[9/23/2019, 2:23:34 PM] [NeatoVacuumRobot] Adding zone cleaning for: Badezimmer
stdout
12:23:34
[9/23/2019, 2:23:34 PM] [NeatoVacuumRobot] Adding zone cleaning for: Abstellkammer
stdout
12:23:34
[9/23/2019, 2:23:34 PM] [NeatoVacuumRobot] Initializing platform accessory 'Elvis'...
stdout
12:23:34
HAP Warning: Characteristic undefined not in required or optional characteristics for service 00000049-0000-1000-8000-0026BB765291. Adding anyway.
stdout
12:23:34
[9/23/2019, 2:23:34 PM] [NeatoVacuumRobot] Error getting robot meta information: Error: Cannot add a Characteristic with the same UUID as another Characteristic in this Service: 1E79C603-63B8-4E6A-9CE1-D31D67981831: null
stdout
12:23:34
[9/23/2019, 2:23:34 PM] [NeatoVacuumRobot] Found robot #1 named "Elvis" with serial "xxxxxxxxxxxxxxxxxxx"
stdout
12:23:34
[9/23/2019, 2:23:34 PM] [NeatoVacuumRobot] Adding zone cleaning for: Schlafzimmer 2
stdout
12:23:34
[9/23/2019, 2:23:34 PM] [NeatoVacuumRobot] Adding zone cleaning for: Esszimmer 2
stdout
12:23:34
[9/23/2019, 2:23:34 PM] [NeatoVacuumRobot] Adding zone cleaning for: Wohnzimmer 2
stdout
12:23:34
[9/23/2019, 2:23:34 PM] [NeatoVacuumRobot] Adding zone cleaning for: Flur 2
stdout
12:23:34
[9/23/2019, 2:23:34 PM] [NeatoVacuumRobot] Adding zone cleaning for: Kinderzimmer 2
stdout
12:23:34
[9/23/2019, 2:23:34 PM] [NeatoVacuumRobot] Adding zone cleaning for: Küche 2
stdout
12:23:34
[9/23/2019, 2:23:34 PM] [NeatoVacuumRobot] Adding zone cleaning for: Badezimmer 2
stdout
12:23:34
[9/23/2019, 2:23:34 PM] [NeatoVacuumRobot] Adding zone cleaning for: Abstellkammer 2
stdout
12:23:34
(node:3291) UnhandledPromiseRejectionWarning: Error: This callback function has already been called by someone else; it can only be called one time.
stdout
12:23:34
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12:13
stdout
12:23:34
    at getRobots (/homebridge/node_modules/homebridge-neato/index.js:90:4)
stdout
12:23:34
    at robot.getState (/homebridge/node_modules/homebridge-neato/index.js:171:15)
stdout
12:23:34
    at Robot.<anonymous> (/homebridge/node_modules/homebridge-neato/node_modules/node-botvac/lib/robot.js:39:17)
stdout
12:23:34
    at /homebridge/node_modules/homebridge-neato/node_modules/node-botvac/lib/robot.js:482:17
stdout
12:23:34
    at /homebridge/node_modules/homebridge-neato/node_modules/node-botvac/lib/api.js:34:45
stdout
12:23:34
    at process._tickCallback (internal/process/next_tick.js:68:7)
stdout
12:23:34
(node:3291) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
stdout
12:23:34
(node:3291) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
stdout
12:23:34
HAP Warning: Characteristic undefined not in required or optional characteristics for service 00000049-0000-1000-8000-0026BB765291. Adding anyway.
stdout
12:23:34
[9/23/2019, 2:23:34 PM] [NeatoVacuumRobot] Cannot update robot. Check if robot is online. Error: Cannot add a Characteristic with the same UUID as another Characteristic in this Service: A7889A9A-2F27-4293-BEF8-3FE805B36F4E
stdout
12:23:34
HAP Warning: Characteristic undefined not in required or optional characteristics for service 00000049-0000-1000-8000-0026BB765291. Adding anyway.
stdout
12:23:34
(node:3291) UnhandledPromiseRejectionWarning: Error: Cannot add a Characteristic with the same UUID as another Characteristic in this Service: A7889A9A-2F27-4293-BEF8-3FE805B36F4E
stdout
12:23:34
    at Service.Switch.Service.addCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Service.js:80:13)
stdout
12:23:34
    at Service.Switch.Service.getCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Service.js:162:19)
stdout
12:23:34
    at Service.Switch.Service.setCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Service.js:183:8)
stdout
12:23:34
    at NeatoVacuumRobotAccessory.updated (/homebridge/node_modules/homebridge-neato/accessories/neatoVacuumRobot.js:689:35)
stdout
12:23:34
    at updateRobot (/homebridge/node_modules/homebridge-neato/index.js:243:24)
stdout
12:23:34
    at robot.device.getState (/homebridge/node_modules/homebridge-neato/index.js:216:5)
```

**Comment by naofireblade** [comment]
Hey thanks for testing and reporting back. Beta 8 should start now and includes
- find me function
- spot cleaning (individual spot size on D7)
- firmware and device info
- a lot of fixes for the room cleaning

**Comment by Krocko** [comment]
Installed beta 8 without problems. 
I can not find the "find me" function. 
What does the `Spot ↺` switch?

**Comment by naofireblade** [comment]
woops u installed beta 7. I forgot to publish beta 8 :D
Find me is now there and the ↺ enables cleaning the spot twice. I renamed the switch now.

**Comment by Krocko** [comment]
Thank you. 
All is working now.

**Comment by naofireblade** [comment]
Very nice to hear. Thank u!
