### ISSUE TITLE
Error with non smart robots in account

### ISSUE THREAD

**Issue by naofireblade** [naofireblade/homebridge-neato#49]
My account
https://user-images.githubusercontent.com/20209851/71785259-8eddf980-2fcb-11ea-8b99-44a5dc8fbad6.png
        {
            "platform": "NeatoVacuumRobot",
            "email": "x@x",
            "password": "xxx"
        }
[1/5/2020, 2:27:20 PM] [NeatoVacuumRobot] Initializing NeatoVacuumRobot platform...
[1/5/2020, 2:27:20 PM] [NeatoVacuumRobot] Refresh is set to: auto
[1/5/2020, 2:27:20 PM] Loading 0 accessories...
[1/5/2020, 2:27:21 PM] [NeatoVacuumRobot] **Error** getting robot meta information: no serial or secret: null
Setup Payload:
X-HM://0023IX8JIE9NF
Scan this code with your HomeKit app

[1/5/2020, 2:27:21 PM] [NeatoVacuumRobot] **Error** getting robot meta information: no serial or secret: null
[1/5/2020, 2:27:21 PM] [NeatoVacuumRobot] Successful login but can't connect to your neato robot: Error: This callback function has already been called by someone else; it can only be called one time.
[1/5/2020, 2:27:21 PM] Homebridge is running on port 51826.
(node:1672) UnhandledPromiseRejectionWarning: Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12:13
    at /usr/local/lib/node_modules/homebridge-**neato**/index.js:116:7
    at /usr/local/lib/node_modules/homebridge-**neato**/index.js:147:7
    at Client.<anonymous> (/usr/local/lib/node_modules/homebridge-neato/node_modules/node-**botvac**/lib/client.js:46:25)
    at /usr/local/lib/node_modules/homebridge-**neato**/node_modules/node-botvac/lib/api.js:34:45
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:1672) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1672) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[1/5/2020, 2:27:22 PM] [WebUI] Homebridge Config UI X v4.6.7 is listening on :: port 8080

_Originally posted by @RCdiy in https://github.com/naofireblade/homebridge-neato/issues/47#issuecomment-570941399_

**Comment by RCdiy** [comment]
Any progress? :)

**Comment by naofireblade** [comment]
Yes, but my neato died and needs to be repaired so I can't debug at the moment :( . I hope I will get him back in 1-2 weeks.

**Comment by RCdiy** [comment]
Will giving you access to my account help?

**Comment by naofireblade** [comment]
I don't wanna do that. But I can provide you a beta release in the next days to test the fix.

**Comment by RCdiy** [comment]
@naofireblade What is the current status of this issue :) Thanks for your work!
