### ISSUE TITLE
Neato Plugin Causing Reboot Loop for Homebridge

### ISSUE THREAD

**Issue by DennisFury** [naofireblade/homebridge-neato#80]
I think this plugin has finally kicked the bucket.  My HB started crashing on this error earlier today.  I rebuilt on new-hardware (was planned anyway) and used new config, getting same crashing message.  The only way to stop the constant homebridge restart is to disable the plugin.

`[21/02/2023, 05:19:48] TypeError: Cannot read properties of undefined (reading 'isCharging')
    at Robot.<anonymous> (/var/lib/homebridge/node_modules/homebridge-neato/node_modules/node-botvac/lib/robot.js:47:50)
    at /var/lib/homebridge/node_modules/homebridge-neato/node_modules/node-botvac/lib/robot.js:610:17
    at /var/lib/homebridge/node_modules/homebridge-neato/node_modules/node-botvac/lib/api.js:40:45
    at <anonymous>
    at processTicksAndRejections (node:internal/process/task_queues:95:5)`

Crash and restart... 
`[21/02/2023, 05:20:31] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[21/02/2023, 05:20:36] [HB Supervisor] Restarting Homebridge...
[21/02/2023, 05:20:36] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution
[21/02/2023, 05:20:36] [HB Supervisor] Started Homebridge v1.6.0 with PID: 11387`

**Comment by jamrogers** [comment]
I have the same issue
